name: "Pre Deployment Script"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repository
        uses: actions/checkout@v2
      - name: Setup and Install Node.Js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Application
        run: yarn run app:build

  build_docker_image_and_push_to_ecr:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to Amazon ECR
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest .
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name ${{ vars.FUNCTION_NAME }} --image-uri ${{ secrets.REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest
